_schema: _schema
source: /src/_includes/
paths:
  uploads: uploads
  static: ''
collections_config:
  data:
    path: src/_data
    name: Data
    icon: data_usage
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
timezone: America/Chicago
markdown:
  engine: commonmark
  options:
    html: true
