[build]
  publish = "public/"
  command = "npm run build"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"
  [[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "public/assets/images", # Processed images - adjust to match your outputDir
    ".cache" # Remote Assets
  ]
[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/admin/*"
  to = "https://lgrua1a8.sanity.studio"
  status = 301
  force = true

[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  SANITY_PROJECT_ID = "lgrua1a8"
  SANITY_DATASET = "production"
  SANITY_API_VERSION = "2023-05-03"